version: "3.7"
services:

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
  
  redis:
    image: redis
    ports:
      - 6379:6379
  
  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1
    environment:
      ELASTIC_URL: http://elasticsearch:9200/
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis  
    networks:
      - elastic
      - default

  flower:  
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - "redis"
      - "worker"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.1"
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - cluster.routing.allocation.disk.threshold_enabled=true
    - cluster.routing.allocation.disk.watermark.low=65%
    - cluster.routing.allocation.disk.watermark.high=70%
    - xpack.security.enabled=true
    - xpack.security.authc.api_key.enabled=true
    - xpack.security.audit.enabled=true
    - xpack.license.self_generated.type=basic
    - ELASTIC_PASSWORD=safest_of_passwords
    ports:
    - "9200:9200"
    networks:
      - elastic

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    command: python app/main.py
    ports:
      - "8888:8888"
    environment:
      PYTHONPATH: .
      ELASTIC_URL: http://elasticsearch:9200/
    depends_on:
      - "elasticsearch"
    networks:
      - elastic
      - default

networks:
  elastic:
    driver: bridge